NewsRss/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace NewsRss.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

NewsRss/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewsRss.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

NewsRss/Pages/NewsPages/NewsAdd.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NewsRss.DomainEvents.Repositories;
using NewsRss.Models;

namespace NewsRss.Pages.NewsPages
{
    public class NewsAddModel : PageModel
    {
        private readonly NewsRepository nRepo;

        public NewsAddModel(NewsRepository newsRepository)
        {
            nRepo = newsRepository;
        }

        [BindProperty]
        public News NewsInput { get; set; }

        [BindProperty]
        public NewsPriorityLevels newsPriorityLevels { get; set; }


        public void OnGet()
        {
        }

        public void OnPostSave()
        {
            if (ModelState.IsValid)
            {
                NewsInput.NewsPriorityLevels = newsPriorityLevels;
                nRepo.Add(NewsInput); 
            }
        }
    }
}

NewsRss/Pages/NewsPages/NewsFeed.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using NewsRss.DomainEvents.Repositories;
using NewsRss.Models;

namespace NewsRss.Pages.NewsPages
{
    public class NewsFeedModel : PageModel
    {
        private readonly NewsRepository nRepo;

        public NewsFeedModel(NewsRepository newsRepository)
        {
            nRepo = newsRepository;
        }
        [BindProperty]
        public News NewsInput { get; set; }

        public List<News> NewsList { get; set; } = new List<News>();



    public void OnGet()
        {
            NewsList = nRepo.List();

            
        }
    }
}

NewsRss/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewsRss.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

NewsRss/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NewsRss/Pages/NewsPages/NewsAdd.cshtml
@page
@model NewsRss.Pages.NewsPages.NewsAddModel
@{
}
<html>
<body >

    <form method="post">

        <label>Name</label>
        <input asp-for="NewsInput.Name" />
        <span asp-validation-for="NewsInput.Name"></span>

        <br />

        <label>RSS URL</label>
        <input asp-for="NewsInput.RSSUrl" />
        <span asp-validation-for="NewsInput.RSSUrl"></span>


        <br />

        <label>Priority</label>

        <ul>

            @foreach (var item in Enum.GetValues(typeof(Models.NewsPriorityLevels)))
            {
            <li>
                @Html.RadioButtonFor(m => m.newsPriorityLevels, item) @item
            </li>
            }
        </ul>


        <div>
            <input type="submit" value="Save" asp-page-handler="Save" />
        </div>

    </form>




</body>
</html>

<script>


</script>

NewsRss/Pages/NewsPages/NewsFeed.cshtml
@page
@model NewsRss.Pages.NewsPages.NewsFeedModel
@{
}

<html>
<body>
 
        <label>Name</label>

        <select onchange="myFunction(event)">
            <option>Choose..</option>
            @foreach (var item in Model.NewsList )
            {
            <option value="@item.RSSUrl">@item.Name</option>
            }
        </select>

        

        <p id="demo"></p>


</body>
</html>

<marquee direction="down" width="100%" height="500" behavior="alternate">
    <div id="news"></div>
</marquee>

<script>

    function myFunction(event) {

        let value = event.target.value;

        fetch(value)
            .then(response => response.text())
            .then(str => new DOMParser().parseFromString(str, "text/xml"))
            .then(data => {

                console.log('data', data);
                const items = data.querySelectorAll("item");

                console.log('items', items);

                let html = '';


                items.forEach(el => {

                    let title = el.querySelector("title").innerHTML.replace("<![CDATA[", "").replace("]]>", "");

                    const description = el.querySelector("description").innerHTML.replace("<![CDATA[", "").replace("]]>", "");

                    html += `
                    <div>
                        <img src="${el.querySelector("link").innerHTML}" alt="">
                        <h2>
                            <a href="${el.querySelector("link").innerHTML}" target="_blank" rel="noopener">
                        ${title}
                        </a>
                        <p style="font-weight: normal;">
                        ${description}
                        </p>
                        </h2>
                    </div>`;
                });


                document.getElementById("news").innerHTML = html;

            })
    }


    
</script>

NewsRss/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NewsRss</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">NewsRss</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - NewsRss - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>